version: '3'
services:
  mongo_cluster:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  inventory:
    build: './inventory'
    environment:
      MONGO_DB_CLUSTER: "mongodb://mongo_cluster:27017"
      MONGO_USER: "root"
      MONGO_PASSWORD: "rootpassword"
    ports:
      - 8080:8080

volumes:
  mongodb_data_container:
